services:

    nginx:
        image: nginx:latest
        restart: unless-stopped
        depends_on:
            - php
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
            interval: 60s
            timeout: 3s
            retries: 3
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html

    php:
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
